spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
    data:  
        mongodb:  
               host: 127.0.0.1  
               port: 27017  
               username:   
               password:   
               database: bonday
               minConnectionsPerHost: 30
               authenticationDatabase:
    resources:
       cache-period: -1

server:
  context-path: /
  port: 8080

#logging:
#  file: /Users/yunge/Desktop/test.log
